name: Archive URL Monthly 1

on:
  schedule:
    - cron: '0 0 1 * *'  # 1st of every month at 00:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Archive URLs
        run: |
          python -c "
          from wayback import save
          save('https://osu.ppy.sh/users/13983108')
          "
