name: Archive URL Monthly

on:
  schedule:
    - cron: '0 2 1 1 *'  # set to work once a year on January 1st
  workflow_dispatch:      # Allows manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Archive the URL
        run: curl -L "https://web.archive.org/save/https://osu.ppy.sh/users/13983108"
