name: Archive URLs Monthly (working one)

on:
  schedule:
    - cron: '0 0 * * 1,5'
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install waybackpy==3.0.6

      - name: Archive URLs
        run: |
          python -c "
          from waybackpy import WaybackMachineSaveAPI
          user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
          with open('links.txt', 'r') as f:
              urls = [line.strip() for line in f if line.strip()]
          for url in urls:
              try:
                  saver = WaybackMachineSaveAPI(url, user_agent)
                  saver.save()
                  print(f'Archived: {url}')
              except Exception as e:
                  print(f'Failed to archive {url}: {e}')
          "
